version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_LINK=$MONGODB_LINK
    networks:
      - backend
      - frontend

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - frontend

volumes:
  mern_app_data:
    driver: local

networks:
  frontend:
  backend:
